/**
 * Local copies of the lifestyle/stock photography from the Stitch design mockups.
 * Downloaded into /public/images/stitch so the site never depends on the design
 * tool's temporary preview CDN. Product photography always comes from Shopify.
 */
const path = (file) => `/images/stitch/${file}`;

export const STOCK_IMAGES = {
  heroLivingSpace: path('ethereal-hearth-living-space-with-large-windows-and.png'),
  rugBurgundy: path('rivareno-modern-burgundy-rug-detail.jpg'),
  rugRust: path('rivareno-modern-rust-rug.jpg'),
  rugBeige: path('rivareno-modern-beige-rug.jpg'),
  rugPinkLines: path('bravo-pink-lines-rug.jpg'),
  roomLiving: path('living-room-collection.png'),
  roomBedroom: path('bedroom-styles.jpg'),
  roomKitchen: path('kitchen-rugs.jpg'),
  roomBathroom: path('bathroom-rug-styles.jpg'),
  foundationTexture: path('refined-rug-textures.jpg'),
  foundationFiberDetail: path('close-up-of-natural-fibers.jpg'),
  instaReadingNook: path('cozy-reading-nook-with-livable-luxury-rug.jpg'),
  instaDiningArea: path('modern-dining-area-with-geometric-rug.jpg'),
  instaPetOnRug: path('pet-dog-on-ivory-rug.jpg'),
  instaHallway: path('sunlit-hallway-with-runner-rug.jpg'),
  instaMoodyBedroom: path('moody-bedroom-with-rust-rug.jpg'),
  mobileKitchenRunner: path('expansive-kitchen-with-a-sophisticated-runner-rug.jpg'),
  mobileBedroom: path('bedroom-with-high-design-rug.jpg'),
  mobileOutdoorPatio: path('outdoor-patio-with-durable-flat-weave-rug.jpg'),
  sageGreenRug: path('impasto-sage-green-rug.jpg'),
  linearOasisGreenRug: path('linear-oasis-green-rug.jpg'),
  washableDemo: path('functionality-demonstration.jpg'),
  socialProof1: path('social-proof-image-1.jpg'),
  socialProof2: path('social-proof-image-2.jpg'),
  socialProof3: path('social-proof-image-3.jpg'),
  socialProof4: path('social-proof-image-4.jpg'),
  pdpThumbWeave: path('detailed-weave-pattern-of-impasto-sage-rug.jpg'),
  pdpThumbLifestyle: path('lifestyle-view-of-impasto-sage-rug-in-living.jpg'),
  pdpThumbTexture: path('close-up-of-rug-pile-texture.jpg'),
  pdpMain: path('full-view-of-impasto-sage-rug.jpg'),
  styledDiningRoom: path('rug-close-up-with-decor.jpg'),
  styledDetail: path('detail-of-rug-texture.jpg'),
  styledHomeOffice: path('rug-in-a-home-office-setting.jpg'),
  relatedOmbreMirage: path('ombr-mirage-rug.jpg'),
  relatedMidnightTrellis: path('midnight-trellis.jpg'),
  relatedFoundationNeutral: path('foundation-neutral.jpg'),
  tradeTextureDetail: path('close-up-detail-of-a-high-end-textured.jpg'),
  moodyHero: path('moody-textures-layered-rugs-hero.webp'),
  executiveOffice: path('executive-office-city-view.jpg'),
  bohoHomeOfficeDesk: path('boho-home-office-desk.jpg'),
  overheadTexturedRug: path('overhead-textured-wool-rug-with-leather-chair.jpg'),
};
